export const JWT_PUBLIC_KEY =
  process.env.JWT_PUBLIC_KEY ||
  `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm08QQNaozwoUDFZzgLwZ
J7CqxunfWlVn8JqMjaC1GkvGg6E2L8zQc2jQ5cDKviDM0ibLtwtlPF1QOTHirm4Y
KTmFAd2gn0cIveZGYxlYJSNe7v0b0WdL9ykvjM/xAAqvEXYtuL/AXk2pZsTqmy3B
FpaVUziW76IWllLWyGcjtMCpDHZrMaC9cDyLlPhIBWbUi2ZZwMKHjLXfkxC3bFgv
ZdPFQsiFZt+EG8b5My0axXD6kSy+AXIDlDOAjiby5FZMTYyaccTzmk7e5vcHS3HE
qc5bIY1rwkoXhtDAw2HH2u1XJnrhwQPXDukJSmnYK0k6u/xnWHCRfXDyP9f7S3AX
2QIDAQAB
-----END PUBLIC KEY-----`;
